#drug.rq

base <https://go.drugbank.com/drugs/> 
prefix ex:<http://example.com/>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?drug ex:name ?name_drug.
          
}
WHERE {
    # Create an URI for each drug base on the column "id"
    BIND(iri(?id) as ?drug)
    BIND(xsd:string(?name) as ?name_drug)
}