#interaction.rq

prefix drug:<https://go.drugbank.com/drugs/> 
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ex:<http://example.com/>

CONSTRUCT {
    ?drug1 ex:interactWith ?drug2;
           a "source_drug".
    ?drug2 a "target_drug".

}
WHERE {
    # Create an URI for each condition or pathology base on the column "id"
    BIND(iri(CONCAT("https://go.drugbank.com/drugs/",?source_drug_id)) as ?drug1)
    BIND(iri(CONCAT("https://go.drugbank.com/drugs/",?target_drug_id)) as ?drug2)

    
}