#source.rq

prefix src:<http://example.com/id_source/>
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ex:<http://example.com/>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?source ex:name ?name_source;
            ex:url ?url_source;
            a ex:Source.

}
WHERE {
    #Create an URI for each source base on the column id
    BIND(iri(CONCAT("http://example.com/id_source/", ?id)) as ?source)
    BIND(xsd:string(?name) as ?name_source)
    BIND(xsd:anyURI(?url) as ?url_source)
}