#store.rq

prefix store:<http://example.com/id_store/>
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ex:<http://example.com/>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?store ex:name ?name_store.     
}
WHERE {
    BIND(iri(CONCAT("http://example.com/id_store/",?id)) as ?store)
    BIND(xsd:string(?name) as ?name_store)
}